USE [master]
GO
/****** Object:  Database [db_UsrManagment]    Script Date: 16-05-2024 13:05:30 ******/
CREATE DATABASE [db_UsrManagment]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_UsrManagment', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\db_UsrManagment.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'db_UsrManagment_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\db_UsrManagment_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [db_UsrManagment] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_UsrManagment].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [db_UsrManagment] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [db_UsrManagment] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [db_UsrManagment] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [db_UsrManagment] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [db_UsrManagment] SET ARITHABORT OFF 
GO
ALTER DATABASE [db_UsrManagment] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [db_UsrManagment] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [db_UsrManagment] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [db_UsrManagment] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [db_UsrManagment] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [db_UsrManagment] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [db_UsrManagment] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [db_UsrManagment] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [db_UsrManagment] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [db_UsrManagment] SET  DISABLE_BROKER 
GO
ALTER DATABASE [db_UsrManagment] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [db_UsrManagment] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [db_UsrManagment] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [db_UsrManagment] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [db_UsrManagment] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [db_UsrManagment] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [db_UsrManagment] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [db_UsrManagment] SET RECOVERY FULL 
GO
ALTER DATABASE [db_UsrManagment] SET  MULTI_USER 
GO
ALTER DATABASE [db_UsrManagment] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [db_UsrManagment] SET DB_CHAINING OFF 
GO
ALTER DATABASE [db_UsrManagment] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [db_UsrManagment] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [db_UsrManagment] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [db_UsrManagment] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'db_UsrManagment', N'ON'
GO
ALTER DATABASE [db_UsrManagment] SET QUERY_STORE = ON
GO
ALTER DATABASE [db_UsrManagment] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [db_UsrManagment]
GO
/****** Object:  Table [dbo].[AuditEntry]    Script Date: 16-05-2024 13:05:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AuditEntry](
	[AuditEntryID] [int] IDENTITY(1,1) NOT NULL,
	[EntitySetName] [nvarchar](255) NULL,
	[EntityTypeName] [nvarchar](255) NULL,
	[State] [int] NOT NULL,
	[StateName] [nvarchar](255) NULL,
	[CreatedBy] [nvarchar](255) NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
	[Discriminator] [nvarchar](max) NOT NULL,
	[AppplicationName] [nvarchar](max) NULL,
 CONSTRAINT [PK_AuditEntry] PRIMARY KEY CLUSTERED 
(
	[AuditEntryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AuditEntryProperty]    Script Date: 16-05-2024 13:05:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AuditEntryProperty](
	[AuditEntryPropertyID] [int] IDENTITY(1,1) NOT NULL,
	[AuditEntryID] [int] NOT NULL,
	[RelationName] [nvarchar](255) NULL,
	[PropertyName] [nvarchar](255) NULL,
	[OldValue] [nvarchar](max) NULL,
	[NewValue] [nvarchar](max) NULL,
	[Discriminator] [nvarchar](max) NOT NULL,
	[AppplicationName] [nvarchar](max) NULL,
 CONSTRAINT [PK_AuditEntryProperty] PRIMARY KEY CLUSTERED 
(
	[AuditEntryPropertyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 16-05-2024 13:05:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Role] [int] NOT NULL,
	[UserName] [varchar](80) NOT NULL,
	[FirstName] [varchar](80) NOT NULL,
	[LastName] [varchar](80) NOT NULL,
	[MobileNo] [varchar](10) NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[PasswordHash] [varchar](160) NOT NULL,
	[PasswordSalt] [varchar](80) NOT NULL,
	[GAuthRequired] [bit] NULL,
	[GAuthAccountKey] [varchar](140) NULL,
UNIQUE NONCLUSTERED 
(
	[UserName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [db_UsrManagment] SET  READ_WRITE 
GO
